### ISSUE TITLE
more ideas

### ISSUE THREAD

**Issue by mattdesl** [polyrepo/polyrepo#1]
Some more things I tend to need:
- check for 404 links in readmes (eg with [gh-md-urls](https://github.com/mattdesl/gh-md-urls))
- view all open PRs; with filtering (eg ignore those created by you)
- managing repos across not just a single user, but also multiple orgs (stackgl, jam3, etc)
- renaming a module
- transfer ownership of a module and change "repository" field in package.json
- prune all node_modules in a folder (save a bit of disk space)

**Comment by yoshuawuyts** [comment]
@mattdesl sounds cool! I've added you to the organization; feel free to create repo's where you see fit. The idea @hughsk and I had is to create `polyrepo-<name>` CLI tools that can then be aggregated under the `polyrepo` command, just like git does! :sparkles:

**Comment by mattdesl** [comment]
Thanks. :tada: 

Other things which we tend to run into on large team projects:
- fixing a bug in a module deep in your dependency tree by forking a bunch of its dependents
- easier diffs of node_module versions to find out why something works on machine A but not on machine B

**Comment by yoshuawuyts** [comment]
Added your suggestions in c60597, feel free to add more as you come up with them!
